// import React, { useEffect } from "react";
// import type { InferGetServerSidePropsType, GetServerSideProps } from 'next'
 
// type Repo = {
//   name: string
//   stargazers_count: number
// }

// export default function Page({repo}) {
//     useEffect(() => {
        
//     })
//   return <div>page</div>;
// }

// // export const getServerSideProps: GetServerSideProps<{
// //     repo: Repo
// //   }> = async () => {
// //     const res = await fetch('https://api.github.com/repos/vercel/next.js')
// //     const repo = await res.json()
// //     return { props: { repo } }
// //   }

// export const getServerSideProps = function(){
//   axios.get(
            
//     )
//   return { props: { repo } }
// }